services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssh_config:/var/jenkins_home/.ssh
    restart: unless-stopped
    
volumes:
  jenkins_jenkins_home:
    external: true
#    driver: local