version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: jenkins-server:custom
    container_name: jenkins-server
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_ssh:/var/jenkins_home/.ssh:ro
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""
    restart: unless-stopped
    networks:
      - jenkins-network

  jenkins-agent-1:
    image: jenkins-agent:custom
    container_name: jenkins-agent-1
    env_file:
      - .agent1.env
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: "agent1"
    depends_on:
      - jenkins
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ./jenkins_ssh:/home/jenkins/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent-2:
    image: jenkins-agent:custom
    container_name: jenkins-agent-2
    env_file:
      - .agent2.env
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: "agent2"
    depends_on:
      - jenkins
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ./jenkins_ssh:/home/jenkins/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
  
networks:
  jenkins-network:
    driver: bridge
