services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_ssh:/var/jenkins_home/.ssh
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""
    restart: unless-stopped
    networks:
      - jenkins-network

  dind:
    image: docker:dind
    container_name: dind
    privileged: true  
    environment:
      DOCKER_TLS_CERTDIR: ""  
    networks:
      - jenkins-network
    volumes:
      - dind-storage:/var/lib/docker 

  jenkins-agent-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent-1
    env_file:
      - .agent1.env
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: "agent1"
      DOCKER_HOST: tcp://dind:2375  # Conecta ao serviço DinD
    depends_on:
      - jenkins
      - dind
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_ssh:/home/jenkins/.ssh/

  jenkins-agent-2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent-2
    env_file:
      - .agent2.env
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: "agent2"
      DOCKER_HOST: tcp://dind:2375  # Conecta ao serviço DinD
    depends_on:
      - jenkins
      - dind
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_ssh:/home/jenkins/.ssh/

  jmeter:
    image: justb4/jmeter
    container_name: jmeter
    networks:
      - jenkins-network
    restart: unless-stopped


  cypress:
    image: cypress/included:latest
    container_name: cypress
    volumes:
      - ./cypress:/e2e
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
  dind-storage:

networks:
  jenkins-network:
    driver: bridge
